CREATE TABLE list (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    board_id INTEGER NOT NULL,
    FOREIGN KEY (board_id) REFERENCES board(id)
);

